version: '3.1'

services:

  # optional local database (change MONGO_URL to switch DB)
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    
    ports:
      - 27017:27017
    
    volumes:
      - ./data/mongo_db:/data/db
  
  # mertics
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # auth
  auth:
    build: ./services/auth-service
    restart: always
    environment:
      API_ROOT_PATH: "/api/v1/auth"
      API_HTTP_PORT: "8080"
      API_DB_NAME: "auth_service"
      API_TOKEN_EXPIRE_MIN: "60"
    volumes:
      - "./.env:/app/.env"
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  # "todo" example microservice
  todo-example:
    build: ./services/todo-example-microservice
    restart: always
    environment:
      API_ROOT_PATH: "/api/v1/todo"
      API_HTTP_PORT: "8080"
      API_DB_NAME: "todo_service"
    volumes:
      - "./.env:/app/.env"
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
  
  router:
    build: ./router/
    ports:
        - "8080:80"
    depends_on:
        - auth
        - todo-example
